version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.13

    working_directory: /go/src/github.com/edgeware/go-rtmp

    environment:
      TEST_RESULTS: /tmp/test-results

    steps:
      - checkout

      - run: mkdir -p $TEST_RESULTS

      - restore_cache:
          keys:
            - v1-pkg-cache

      - run: go get github.com/jstemmer/go-junit-report
      - run: go get github.com/haya14busa/goverage
      - run: go get github.com/mattn/goveralls

      - run:
          name: Run unittests
          command: |
            trap "go-junit-report <${TEST_RESULTS}/go-test.out > ${TEST_RESULTS}/go-test-report.xml" EXIT
            make test | tee ${TEST_RESULTS}/go-test.out

      - run:
          name: Run linter
          command: |
            make lint

      - store_test_results:
          path: /tmp/test-results

      - run:
          name: Measure coverage
          command: goverage -coverprofile=/tmp/coverage.out ./...

      #- run:
      #    name: Send coverage
      #    command: goveralls -coverprofile=/tmp/coverage.out -service=circle-ci -repotoken=$COVERALLS_TOKEN

workflows:
  version: 2
  commit:
    jobs:
      - build
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build
